services:
  web:
    build:
      context: ./ui-web
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - api
      - mediamtx
    restart: unless-stopped

  api:
    build:
      context: ./backend-api
    env_file:
      - ./backend-api/.env
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Ho_Chi_Minh
      RTSP_HOST: mediamtx
      RTSP_PORT: 8554
      PUBLIC_HLS_BASE_URL: /hls
    expose:
      - "3000"
    volumes:
      - ./backend-api/uploads:/app/uploads
    depends_on:
      - mediamtx
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    expose:
      - "8554"
      - "8888"
    restart: unless-stopped
